# Site settings
title: JayGreentree.Blog
header-img: img/home-bg.jpg
email: 
copyright_name: MindFusion Development
description: "Latest updates on development projects"
baseurl: ""
url: "http://mindfusion-hosting-solutions.github.io"
twitter_username: JayTheITGuy1983
github_username:  jaygreentree
facebook_username:  
email_username:  
# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate, jekyll-feed]
